### ISSUE TITLE
UI - urwid.listbox.ListWalkerError: SimpleListWalker expecting list like object, got: None

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/scenario-player#131]
The dev as well as the master branch give this error. 
https://gist.github.com/agatsoh/0cadd47e882dfee35b287b8c1613f1a5

On dev branch I am on this commit 
```
(raiden_env) [krishna@krishna-pc scenario-player]$ git log
commit 12db4ec8f9037dd418ac10e8cb74780ff613008f (HEAD -> dev, tag: v0.1.0-dev16, upstream/dev)
Author: DevOpsBot <contact@brainbot.li>
Date:   Thu Jul 25 09:01:37 2019 +0000

    Cut New Release: 0.1.0-dev15 → 0.1.0-dev16
```

On master I am on this commit

```
(raiden_env) [krishna@krishna-pc scenario-player]$ git log
commit 8c90d7e74fd075195050048cb972bcdf5ef9fa71 (HEAD -> master, tag: v0.1.1, upstream/master, origin/master, origin/HEAD)
Author: DevOpsBot <contact@brainbot.li>
Date:   Wed Jul 24 18:57:24 2019 +0000

    Cut New Release: 0.1.0-dev15 → 0.1.1

```

**Comment by palango** [comment]
Same for me:
```
(venv) ➜  scenario-player git:(master) python -m scenario_player --chain=goerli:http://geth.goerli.ethnodes.brainbot.com:8545  run --keystore-file ~/Library/Ethereum/rinkeby/keystore/UTC--2017-10-06T13-21-31.629952592Z--32daa921c25480aa8f3803c33869be95df1b06b0 --password=0 ../raiden/raiden/tests/scenarios/pfs5_too_low_capacity.yaml
Writing log to /Users/paul/.raiden/scenario-player/scenarios/pfs5_too_low_capacity/scenario-player-run_pfs5_too_low_capacity_2019-07-31T15:49:40.log
2019-07-31 13:49:41.339327 [info     ] Using account                  [scenario_player.main] account=0x32dAA921C25480aA8f3803c33869be95Df1B06b0
 * Serving Flask app "scenario_player.services.utils.factories" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/__main__.py", line 9, in <module>
    main()
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 175, in run
    ui = ScenarioUI(runner, log_buffer, log_file_name)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/ui.py", line 199, in __init__
    self._log_box = uwd.LineBox(self._log_widget, title="Log", title_align="left")
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/ui.py", line 241, in _log_widget
    return uwd.ListBox(self._log_walker)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/urwid/listbox.py", line 283, in __init__
    self.body = body
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/urwid/listbox.py", line 318, in _set_body
    self._body = SimpleListWalker(body)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/urwid/listbox.py", line 145, in __init__
    raise ListWalkerError("SimpleListWalker expecting list like object, got: %r"%(contents,))
urwid.listbox.ListWalkerError: SimpleListWalker expecting list like object, got: None

**Comment by christianbrb** [comment]
@nlsdfnbch Is this the error which is just happening in interactive mode?
