### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#134]
When trying to run the SP locally today I get the following error. I followed the instructions from the readme to install raiden and then the SP in the same venv like I always do. 

```
Writing log to /home/jacob/.raiden/scenario-player/scenarios/pfs7_simple_path_rewards/scenario-player-run_pfs7_simple_path_rewards_2019-07-29T12:43:11.log
2019-07-29 10:43:12.213609 [info     ] Using account                  [scenario_player.main] account=0x0bae0289AAA26845224F528F9B9DefE69e01606E
 * Serving Flask app "scenario_player.services.utils.factories" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/jacob/venvs/.venvRaiden/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/scenario_player/main.py", line 170, in run
    account, chain_rpc_urls, auth, data_path, scenario_file, notify_tasks_callable
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/scenario_player/runner.py", line 60, in __init__
    from scenario_player.node_support import RaidenReleaseKeeper, NodeController
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/scenario_player/node_support.py", line 32, in <module>
    from raiden.ui.cli import run as cli_run
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/ui/cli.py", line 19, in <module>
    from raiden.app import App
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/app.py", line 11, in <module>
    from raiden.raiden_service import RaidenService
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/raiden_service.py", line 17, in <module>
    from raiden.blockchain.decode import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/blockchain/decode.py", line 7, in <module>
    from raiden.blockchain.state import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/blockchain/state.py", line 8, in <module>
    from raiden.storage.restore import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/storage/restore.py", line 4, in <module>
    from raiden.storage.sqlite import (
  File "/home/jacob/venvs/.venvRaiden/lib/python3.7/site-packages/raiden/storage/sqlite.py", line 8, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by czepluch** [comment]
Closing this, since it's not related to the SP, but happens when starting Raiden. Issue in Raiden repo: https://github.com/raiden-network/raiden/issues/4473
