### ISSUE TITLE
Failing scenarios - pfs2/3_simple_no_path - 31.07.2019

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#148]
DevOpsBot 08:39
Starting run for scenarios ‘pfs3_multiple_paths’..

DevOpsBot 08:41
❌ Error while running scenario: scenario error!

Traceback (most recent call last):
```
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 181, in run
    runner.run_scenario()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/runner.py", line 208, in run_scenario
    raise TokenRegistrationError(msg)
scenario_player.exceptions.legacy.TokenRegistrationError: HTTPConnectionPool(host='127.0.0.1', port=56231): Max retries exceeded with url: /api/v1/tokens/0xfDc041CeFf07C84Dc2fa31c0D52aD352bc385db6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb1e9ab70b8>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Log can be downloaded from:
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs3_multiple_paths-1-latest-2019-07-31.tar.gz

**Comment by christianbrb** [comment]
pfs3_multiple_paths failed with the same error

**Comment by christianbrb** [comment]
Root Cause: https://github.com/raiden-network/raiden/issues/4434
