### ISSUE TITLE
RESTAPIStatusMismatchError / Internal server error

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#178]
Failed on 03.08.2019 (PFS Scenarios)

http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs1_get_a_simple_path-1-latest-2019-08-03.tar.gz
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs3_multiple_paths-1-latest-2019-08-03.tar.gz
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs4_use_best_path-1-latest-2019-08-03.tar.gz
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs5_too_low_capacity-1-latest-2019-08-03.tar.gz
http://scenario-player.ci.raiden.network/Scenario_player_Logs-pfs6_low_capacity-1-latest-2019-08-03.tar.gz

Failed on 04.08.2019 (MS scenario)

http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms2_simple_monitoring-1-latest-2019-08-04.tar.gz

Failed on 05.08.2019 (PFS scenario)
http://scenario-player.ci.raiden.network/Scenario_player_Logs-ms2_simple_monitoring-1-latest-2019-08-04.tar.gz

**Comment by palango** [comment]
From the logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/webargs/core.py", line 464, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/raiden/api/v1/resources.py", line 52, in put
    registry_address=self.rest_api.raiden_api.raiden.default_registry.address, **kwargs
  File "/usr/local/lib/python3.7/site-packages/raiden/api/rest.py", line 641, in open
    total_deposit=total_deposit,
  File "/usr/local/lib/python3.7/site-packages/raiden/api/python.py", line 663, in set_total_channel_deposit
    channel_proxy.set_total_deposit(total_deposit=total_deposit, block_identifier=blockhash)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/payment_channel.py", line 161, in set_total_deposit
    partner=self.participant2,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network.py", line 837, in set_total_deposit
    log_details=log_details,
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token_network.py", line 869, in _set_total_deposit
    self.token.approve(allowed_address=Address(self.address), allowance=amount_to_deposit)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/proxies/token.py", line 89, in approve
    receipt = self.client.poll(transaction_hash)
  File "/usr/local/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 675, in poll
    raise Exception("invalid transaction, check gas price")
Exception: invalid transaction, check gas price

**Comment by christianbrb** [comment]
Root Cause seems to be https://github.com/raiden-network/raiden/issues/4529
