### ISSUE TITLE
Scenario player fails to unlock account

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/scenario-player#185]
```
Traceback (most recent call last):
  File "/home/hack/work/scenario_player_venv/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/scenario_player/main.py", line 142, in run
    account = load_account_obj(keystore_file, password)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/scenario_player/main.py", line 84, in load_account_obj
    account = Account(json.load(keystore), password, keystore_file)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/raiden/accounts.py", line 155, in __init__
    self.unlock(password)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/raiden/accounts.py", 
line 167, in unlock
    self._privkey = decode_keyfile_json(self.keystore, password.encode("UTF-8"))
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/eth_keyfile/keyfile.py", line 49, in decode_keyfile_json
    return _decode_keyfile_json_v3(keyfile_json, password)
  File "/home/hack/work/scenario_player_venv/lib/python3.7/site-packages/eth_keyfile/keyfile.py", line 170, in _decode_keyfile_json_v3
    raise ValueError("MAC mismatch")
ValueError: MAC mismatch
```

Raiden version:

```
{
  "raiden": "0.100.5.dev37+g50c090cdb",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.3",
  "system": "Linux 64bit_ELF 5.1.16.a-1-hardened",
  "architecture": "x86_64",
  "distribution": "source"
}
```

scenario_player version (`pip freeze | grep scenario`):

raiden-scenario-player==0.1.1
29184753ea955e0f82520b5f150be752ea884297

Steps to reproduce:

```
parity --keys-path=$(pwd)/keys --base-path=$(pwd) account new
parity --keys-path=$(pwd)/keys2 --base-path=$(pwd) account import $(pwd)/keys/ethereum/UTC--*
geth --keystore $(pwd)/keys2/ethereum account update ${account_address}
```

Notes:
- The account was created without a password, that is why I'm reimporting it
- I have not checked if there is a shorter step to produce the above stacktrace, maybe the problem is only with the geth update
- The geth updated added a password

**Comment by hackaugusto** [comment]
This is not a bug, see #187
