### ISSUE TITLE
raiden_version: local and missing executable should fail with better error

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/scenario-player#211]
## Problem definition

I used `raiden_version: local` in a scenario and it failed by not being able to start raiden. 

The scenario player itself failed with:

```
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lefteris/ew/scenario-player/scenario_player/__main__.py", line 9, in <module>
    main()
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/ew/scenario-player/scenario_player/main.py", line 222, in run
    service_process.start()
  File "/usr/lib64/python3.7/multiprocessing/process.py", line 106, in start
    assert self._popen is None, 'cannot start a process twic
```

and then looking at the node logs I see this at the stderr:

```
--------- Starting ---------
Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/raiden/utils/__init__.py", line 136, in get_system_spec
    version = pkg_resources.require(raiden.__name__)[0].version
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Flask 1.1.1 (/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages), Requirement.parse('flask==1.0.3'), {'raiden'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/scenarioplayer/bin/raiden", line 10, in <module>
    sys.exit(main())
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/raiden/__main__.py", line 13, in main
    run(auto_envvar_prefix="RAIDEN")  # pylint: disable=no-value-for-parameter
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/raiden/ui/cli.py", line 458, in run
    click.secho(runner.welcome_string, fg="green")
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/raiden/ui/runners.py", line 52, in welcome_string
    return f"Welcome to Raiden, version {get_system_spec()['raiden']}!"
  File "/home/lefteris/.virtualenvs/scenarioplayer/lib/python3.7/site-packages/raiden/utils/__init__.py", line 139, in get_system_spec
    "Cannot detect Raiden version. Did you do python setup.py?  "
RuntimeError: Cannot detect Raiden version. Did you do python setup.py?  Refer to https://raiden-network.readthedocs.io/en/latest/overview_and_guide.html#for-developers
--------- Stopped ---------
```

## Task

Since `which raiden` returns nothing I would expect a failure indeed but a better error can be given.

**Comment by nlsdfnbch** [comment]
"better" is subject to personal opinion - can you be more specific?

I suggest the following:

when using `local`, and no raiden found in env -> Raise `MissingRaidenInstallation("`which raiden` returned None!")`
when stating a path to the binary , a `FileNotFoundError` should be raised.

Would that suffice for you? Or are you missing more information?

**Comment by LefterisJP** [comment]
That would be perfect!

So my end goal is my past self would not have needed to ask you in the chat why the error, but the error would have explained to me what was wrong.

**Comment by palango** [comment]
This is now shown:
```
FileNotFoundError: Could not use local binary 'raiden234234'! No Binary found in env!
```
