### ISSUE TITLE
InsufficientMintingAmount Exception 

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/scenario-player#268]
Description
=========
The commit of the dev branch that I am testing on
```
(raiden_env) [krishna@krishna-pc scenario-player]$ git log
commit 60b359899a3385d82e2d71da8f57dacce8789111 (HEAD -> dev, upstream/dev)
Author: DevOpsBot <contact@brainbot.li>
Date:   Fri Aug 23 08:04:57 2019 +0000

    'Sync Branch Versions.'

commit a67f951f8d065a2cfa98a1af83a9148dca378672
Merge: 5c8d0f1 2dbe8f4
Author: Nils Diefenbach <nlsdfnbch.foss@kolabnow.com>
Date:   Fri Aug 23 10:03:31 2019 +0200

    [HOTFIX-#264] Reset Dev to 0.3.5 and pick feat/fix commits.
    
    Master at 0.3.5

```

One the latest dev branch I run the same [scenario](https://github.com/czepluch/raiden/blob/multiple_payments_pfs_scenario/raiden/tests/scenarios/pfs7_multiple_payments.yaml) in issue #238 and get [this](https://gist.github.com/agatsoh/c664e91d0f760fb2cbeb90604bd8a3de) error
 A small snapshot from the stacktrace of the error

```
Traceback (most recent call last):
  File "/home/krishna/Envs/raiden_env/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/scenario_player/main.py", line 214, in run
    account, chain_rpc_urls, auth, data_path, scenario_file, notify_tasks_callable
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/scenario_player/runner.py", line 71, in __init__
    self.yaml = ScenarioYAML(scenario_file, self.data_path)
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/scenario_player/scenario.py", line 37, in __init__
    self.validate()
  File "/home/krishna/Envs/raiden_env/lib/python3.7/site-packages/scenario_player/scenario.py", line 57, in validate
    raise InsufficientMintingAmount
scenario_player.exceptions.config.InsufficientMintingAmount
```

The scenario player is started 
```
 scenario_player --chain=goerli:http://10.104.6.13:8545 run --no-ui --keystore-file=/home/krishna/.ethereum/keystore/UTC--2019-04-25T07-10-20.510144284Z--1bc9667edcb58197f4a5431fbf0c2289ddc235f3 --password=${KEYSTORE_PW} ~/raidenforked/scenario-player/pfs7_multiple_payments.yaml
```

Expected Behavior
===============
Minting tokens should pass

**Comment by eorituz** [comment]
That is expected if you're running [this PFS7 ](https://github.com/raiden-network/raiden/pull/4619/files)
As the error code says `token.min_balance` isn't high enough.

**Comment by eorituz** [comment]
That is expected, I mentioned it in my review of Jacobs PR
