### ISSUE TITLE
PFS Failure - TokenNetwork does not exist

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#324]
PFS1 failed with the following stacktrace on the SP2 Droplet:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 230, in run
    runner.run_scenario()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/runner.py", line 283, in run_scenario
    gevent.joinall(greenlets, raise_error=True)
  File "src/gevent/greenlet.py", line 849, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 865, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 41, in _run
    task()
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/execution.py", line 65, in _run
    group.join(raise_error=True)
  File "/usr/local/lib/python3.7/site-packages/gevent/pool.py", line 433, in join
    greenlet._raise_exception()
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py", line 74, in __call__
    return self._run(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py", line 59, in _run
    f'HTTP status code "{resp.status_code}" while fetching {url}. '
scenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code "409" while fetching http://127.0.0.1:45803/api/v1/channels. Expected 2..: {"errors": "Token network for token 0x89943C6614E88565a1d0ef2f6dBa180613c39B55 does not exist"}
```
Logs available here:
http://68.183.70.168/Scenario_player_Logs-pfs1_get_a_simple_path-1-latest-2019-09-12.tar.gz
http://68.183.70.168/Scenario_player_Logs-pfs6_simple_path_rewards_same_token-1-latest-2019-09-11.tar.gz
￼
http://68.183.70.168/Scenario_player_Logs-pfs7_multiple_payments-1-latest-2019-09-11.tar.gz

**Comment by Dominik1999** [comment]
see also #318

**Comment by nlsdfnbch** [comment]
Possibly related to #132

**Comment by hackaugusto** [comment]
Yeah, the problem was a race condition on the network registration. [Raw logs](https://gist.github.com/hackaugusto/05df4ddf8e781e08b87bcf9f5e7d02da).
```
"raiden.api.rest":
    "Opening channel"
    "token_address": "0x5c256175fF5B042D10EC01252e94f692a5e15408"

"raiden.blockchain.filters":
    "Querying StatelessFilter"

"raiden.api.rest":
    "Error processing request"
    "errors": "Token network for token 0x5c256175fF5B042D10EC01252e94f692a5e15408 does not exist"

"raiden.raiden_service":
    "token_network_registry_address": "0x603882F4e7fAb5942a585048CADc71F91D6160c5"
    "_type": "raiden.transfer.state_change.ContractReceiveNewTokenNetwork"
```

This is for `pfs6_simple_path_rewards_same_token`, `pfs1_get_a_simple_path` is missing logs and I have not looked into `pfs7_multiple_payments`.

Should be fixed by https://github.com/raiden-network/scenario-player/pull/327
