### ISSUE TITLE
Data Path is no longer a path object

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#389]
After the fix for #8 was merged, the variable is no longer a `pathlib.Path` object and the following error is raised when using the CLI:

```
#!/bin/bash -eo pipefail
scenario_player reclaim-eth \
--data-path=${PROJECT_ROOT} \
--chain goerli:https://${SMOKETEST_NODE} \
--keystore-file=${CI_CONFIG_DIR}/smoketest.keystore \
--password=${SMOKETEST_PW} \
--min-age=1 \

2019-10-30 15:29.02 Using account                  account=0x54b819488D4c864c4098BCA61F1BF840E52D2f38
Traceback (most recent call last):
  File "/home/circleci/ci/venv/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/scenario_player/main.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/scenario_player/main.py", line 166, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/scenario_player/main.py", line 148, in wrapper
    return func(*args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/scenario_player/main.py", line 355, in reclaim_eth
    configure_logging_for_subcommand(construct_log_file_name("reclaim-eth", data_path))
  File "/home/circleci/ci/venv/lib/python3.7/site-packages/scenario_player/main.py", line 68, in construct_log_file_name
    return str(directory.joinpath(file_name))
AttributeError: 'str' object has no attribute 'joinpath'
Exited with code 1
```

Convert the str to a Path object before using it.

**Comment by nlsdfnbch** [comment]
Reason: https://github.com/pallets/click/issues/405
