### ISSUE TITLE
SP is out of funds

### ISSUE THREAD

**Issue by karlb** [raiden-network/scenario-player#485]
```json
{
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/main.py\", line 242, in run\n    account, auth, chain, data_path, scenario_file, notify_tasks_callable\n  File \"/usr/local/lib/python3.7/
site-packages/scenario_player/runner.py\", line 96, in __init__\n    f\"Insufficient balance ({balance / 10 ** 18} Eth) \"\nscenario_player.exceptions.legacy.ScenarioError: Insufficient balance (0.06346399565375256 Eth) in account 0x8f5EA3Bb3E99C317b8745
918F6973f7AfBF659c3 on chain \"goerli\" - it needs additional 0.43653600434624745 Eth (that is 436536004346247434 Wei).",
  "event": "Error during startup",
  "logger": "scenario_player.main",
  "level": "error",
  "timestamp": "2020-02-18 02:00:20.651082"
}
```

**Comment by karlb** [comment]
We didn't reclaim anything for 20 days: https://goerli.etherscan.io/txs?a=0x8f5EA3Bb3E99C317b8745918F6973f7AfBF659c3&f=3

**Comment by karlb** [comment]
When running the reclamation manually I get
```
root@scenario-player2:/var/lib/scenario-player#     docker run \
>         --rm \
>         ${interactive} \
>         -t \
>         -v ${DATA_DIR}:/data \
>         -v ${CONFIG_DIR}:${CONFIG_DIR}:ro \
>         raiden/scenario-player \
>         reclaim-eth \
>         --chain=${CHAIN} \
>         --data-path /data \
>         --keystore-file=${WALLET} \
>         --password=${WALLET_KEY}

2020-02-20 10:18.28 start cmd                      chain=
2020-02-20 10:18.28 using chain                    chain=goerli:http://parity.goerli.ethnodes.brainbot.com:5085
2020-02-20 10:18.30 Using account                  account=0x8f5EA3Bb3E99C317b8745918F6973f7AfBF659c3
Writing log to /data/scenario-player-reclaim-eth_2020-02-20T10:18:30.log
2020-02-20 10:18:30.242172 [info     ] start reclaim                  [scenario_player.main] chain=goerli:http://parity.goerli.ethnodes.brainbot.com:5085                                                                                                    
2020-02-20 10:18:30.243223 [info     ] in cmd                         [scenario_player.utils.legacy] chain=goerli:http://parity.goerli.ethnodes.brainbot.com:5085 chain_name=goerli chain_url=http://parity.goerli.ethnodes.brainbot.com:5085                
2020-02-20 10:18:30.245358 [info     ] Starting eth reclaim           [scenario_player.utils.legacy] data_path=PosixPath('/data')                                                                                                                            
Traceback (most recent call last):
  File "/usr/local/bin/scenario_player", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 112, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 341, in reclaim_eth
    reclaim_eth(min_age_hours=min_age, chain_str=chain, data_path=data_path, account=account)
  File "/usr/local/lib/python3.7/site-packages/scenario_player/utils/legacy.py", line 401, in reclaim_eth
    keyfile_content = json.loads(keyfile.read_text())
  File "/usr/local/lib/python3.7/pathlib.py", line 1200, in read_text
    return f.read()
  File "/usr/local/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```
@nlsdfnbch can you add something to make such errors more visible in the future?

**Comment by karlb** [comment]
The SP tries to read the log files during reclamation, but those are gzipped now, which makes the SP fail.

**Comment by karlb** [comment]
Also some of the key files were xzipped for unknown reasons:
```
/data/scenario-player/scenarios/bf5_join_and_leave/node_510_000/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_509_001/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_509_003/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_509_000/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_510_003/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_510_002/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_509_002/keys/UTC--1.xz
/data/scenario-player/scenarios/bf5_join_and_leave/node_510_001/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_007/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_010/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_006/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_010/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_000/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_009/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_001/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_007/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_011/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_005/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_009/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_008/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_011/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_003/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_012/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_509_000/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_004/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_003/keys/UTC--1.xz
/data/scenario-player/scenarios/bf7_long_path/node_510_013/keys/UTC--1.xz
```
I've unzipped them and now the reclamation works.
