### ISSUE TITLE
Reclaim failed on 03-11

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#524]
See `/var/log/scenario_player/...`
```
^[[2m2020-03-11 21:05:26.471223^[[0m [^[[32m^[[1mdebug    ^[[0m] ^[[1mTransaction to transfer ether will be sent^[[0m [^[[34m^[[1mraiden.network.rpc.client^[[0m] ^[[36meth_node^[[0m=^[[35m<EthClient.PARITY: 'parity'>^[[0m ^[[36mfrom_address^[[0m=^[[35m0x6BeF0F349b30cE67075cEF18bf9792AE0eE4E436^[[0m ^[[36mgas_price^[[0m=^[[35m2000000000^[[0m ^[[36mnode^[[0m=^[[35m0x6BeF0F349b30cE67075cEF18bf9792AE0eE4E436^[[0m ^[[36mnonce^[[0m=^[[35m5^[[0m ^[[36mstartgas^[[0m=^[[35m21000^[[0m ^[[36mto_address^[[0m=^[[35m0x9202584Ac2A5081C6d1F27d637d1DD1Fb2AEc6B7^[[0m ^[[36mtoken^[[0m=^[[35me0167295-b3e2-43d5-85ae-190a55ae8d04^[[0m ^[[36mvalue^[[0m=^[[35m299633787654131263^[[0m^M
^[[2m2020-03-11 21:05:26.497151^[[0m [^[[32m^[[1mdebug    ^[[0m] ^[[1mTransaction sent              ^[[0m [^[[34m^[[1mraiden.network.rpc.client^[[0m] ^[[36meth_node^[[0m=^[[35m<EthClient.PARITY: 'parity'>^[[0m ^[[36mfrom_address^[[0m=^[[35m0x6BeF0F349b30cE67075cEF18bf9792AE0eE4E436^[[0m ^[[36mgas_price^[[0m=^[[35m2000000000^[[0m ^[[36mnode^[[0m=^[[35m0x6BeF0F349b30cE67075cEF18bf9792AE0eE4E436^[[0m ^[[36mnonce^[[0m=^[[35m5^[[0m ^[[36mstartgas^[[0m=^[[35m21000^[[0m ^[[36mto_address^[[0m=^[[35m0x9202584Ac2A5081C6d1F27d637d1DD1Fb2AEc6B7^[[0m ^[[36mtoken^[[0m=^[[35me0167295-b3e2-43d5-85ae-190a55ae8d04^[[0m ^[[36mtransaction_hash^[[0m=^[[35m0xee5d5640c3374df445dc2206c6ec912c7f53e79d565df05c0eba2dbe65b62f87^[[0m ^[[36mvalue^[[0m=^[[35m299633787654131263^[[0m^M
Traceback (most recent call last):^M
  File "/usr/local/bin/scenario_player", line 10, in <module>^M
    sys.exit(main())^M
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__^M
    return self.main(*args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main^M
    rv = self.invoke(ctx)^M
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke^M
    return _process_result(sub_ctx.command.invoke(sub_ctx))^M
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke^M
    return ctx.invoke(self.callback, **ctx.params)^M
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke^M
    return callback(*args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 114, in wrapper^M
    return func(*args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 147, in wrapper^M
    return func(*args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 130, in wrapper^M
    return func(*args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func^M
    return f(get_current_context(), *args, **kwargs)^M
  File "/usr/local/lib/python3.7/site-packages/scenario_player/main.py", line 357, in reclaim_eth^M
    min_age_hours=min_age, chain_str=chain, data_path=data_path, account=account^M
  File "/usr/local/lib/python3.7/site-packages/scenario_player/utils/legacy.py", line 175, in reclaim_eth^M
    gas_price=web3.eth.gasPrice,^M
TypeError: unhashable type: 'TransactionSentImplementation'^M
```

**Comment by karlb** [comment]
I can reproduce this locally, so it does not have anything to do with the nightly run infrastructure.
