### ISSUE TITLE
Lacking allowance while funding UDC

### ISSUE THREAD

**Issue by karlb** [raiden-network/scenario-player#548]
```
2020-04-28 13:28:43.735354 [debug    ] Transaction sent               [raiden.network.rpc.client] args=('0x6eb27c9a8384115EdbD23Bf03A3Dd480C75E6beC', 1000000000000000000) eth_node=<EthClient
.GETH: 'geth'> from_address=0x306089a333E9e01e3bf63DF5954c1Ae1fCcf39E8 function_name=transfer gas_price=9765387150 kwargs={} node=0x306089a333E9e01e3bf63DF5954c1Ae1fCcf39E8 nonce=216 startga
s=67607 to_address=b"k\x17Tt\xe8\x90\x94\xc4M\xa9\x8b\x95N\xed\xea\xc4\x95'\x1d\x0f" token=758a54b8-aa5a-4264-9657-255615fcfd19 transaction_hash=0x3690bf5bbae657a4a06da5dbcd9c21871a7dc6f1a563be4a05959c2f3b13f92b value=0                                                                                                                                                                 
2020-04-28 13:29:14.799315 [warning  ] Process did not exit cleanly   [raiden.utils.nursery] communicate=(None, None) exit_code=1                                                             
2020-04-28 13:29:14.800063 [warning  ] Process did not exit cleanly   [raiden.utils.nursery] communicate=(None, None) exit_code=1                                                             
2020-04-28 13:29:14.800569 [warning  ] Process did not exit cleanly   [raiden.utils.nursery] communicate=(None, None) exit_code=1                                                             
2020-04-28 13:29:14.802499 [warning  ] Process did not exit cleanly   [raiden.utils.nursery] communicate=(None, None) exit_code=1                                                             2020-04-28 13:29:14.803052 [error    ] Exception while running scenario [scenario_player.main]                                                                                                
Traceback (most recent call last):                                                                                                                                                            
  File "/home/karl/scenario-player/scenario_player/main.py", line 321, in run_                                                                                                                    environment=environment,                                                                                                                                                                  
  File "/home/karl/scenario-player/scenario_player/main.py", line 396, in orchestrate                                                                                                         
    scenario_runner.run_scenario()                                                                                                                                                              File "/home/karl/scenario-player/scenario_player/runner.py", line 347, in run_scenario                                                                                                      
    gevent.joinall(greenlets, raise_error=True, count=1)                                                                                                                                      
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall                                                                                                                       
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall                                                                                                                         File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception                                                                                                      
  File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise                                                                                       raise value.with_traceback(tb)                                                                                                                                                              File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run                                                                                                                   
  File "/home/karl/scenario-player/scenario_player/runner.py", line 427, in setup_environment_and_run_main_task                                                                                   pool.join(raise_error=True)                                                                                                                                                                 File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/pool.py", line 435, in join                                                                                        
    greenlet._raise_exception()                                                                                                                                                                 File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception                                                                                                        File "/home/karl/scenario-player/venv/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise                                                                                   
    raise value.with_traceback(tb)                                                                                                                                                              File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run                                                                                                                   
  File "/home/karl/scenario-player/scenario_player/utils/token.py", line 128, in userdeposit_maybe_deposit                                                                                    
    target_address, new_total_deposit, userdeposit_proxy.client.get_confirmed_blockhash()                                                                                                       File "/home/karl/raiden/raiden/network/proxies/user_deposit.py", line 309, in deposit                                                                                                       
    self._deposit_check_result(transaction_hash, token, total_deposit, amount_to_deposit)                                                                                                     
  File "/home/karl/raiden/raiden/network/proxies/user_deposit.py", line 548, in _deposit_check_result                                                                                             raise RaidenRecoverableError(msg)                                                                                                                                                         
raiden.exceptions.RaidenRecoverableError: The allowance is insufficient. Check concurrent deposits for the same token network but different proxies.    
```
Three of four deposits failed:
https://etherscan.io/tx/0x351992d484b079d045eb1780584b01b12a25ba6f0dfb3c60c19ce25af929621d
https://etherscan.io/tx/0xef9a7d1195375733f82c687ddbebe98f65938ce962661b2d3ae509fc141c5678
https://etherscan.io/tx/0x05ac580d5cfb3e45337bc9e532a02d339f2718a77832bc9e3ca8de733949a7e0
https://etherscan.io/tx/0xc58f17344728c3578c64e76334e899b454af67421dd35c8de09450afc9badf9c

When deposit calls are done in parallel in `setup_raiden_nodes_with_sufficient_user_deposit_balances`, but using the same `userdeposit_proxy`. So I would expect the proxy to order the transactions correctly.

**Comment by karlb** [comment]
[scenario-player-run_pfs1_get_a_simple_path_2020-04-28T15:13:43.log](https://github.com/raiden-network/scenario-player/files/4547225/scenario-player-run_pfs1_get_a_simple_path_2020-04-28T15.13.43.log)

**Comment by hackaugusto** [comment]
Humm, so this doesn't seem to be a synchronization problem, but just an arithmetic error somewhere. The code is not doing an approve and deposit for every node, but an approve for all the deposits and then individual deposits:

- from the exception stack trace we known the function `".../utils/token.py", line 128, in userdeposit_maybe_deposit` is being used, which calls [`deposit`](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/utils/token.py#L117-L119) in the UDC, instead of [`approve_and_deposit`](https://github.com/raiden-network/raiden/blob/ccccb18d356547613a6dbeb8b5177105a1eeb746/raiden/network/proxies/user_deposit.py#L311). This is fine since it pretty much 1 transaction per node, which should make things faster.
- the method is properly waiting for the `mint` and the `approve` to happen [here](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/utils/token.py#L114-L115). So the problem has to be with the value of the approval. (Or a bug in the smart contract, but I'm assuming the error is not there).
- the mint and allowance are sent by [another greenlet](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/runner.py#L446-L448) spawned just before the deposit one.
  - The allowance is set to a minimum of [`required_allowance = balance_per_node * node_count`](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/runner.py#L542), where `balance_per_node` is [taken from the scenario configuration](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/runner.py#L536)
   - From the attached log name we know the scenario was pfs1, which [does *not* overwrite the default `balance_per_node`](https://github.com/raiden-network/raiden/blob/ccccb18d356547613a6dbeb8b5177105a1eeb746/raiden/tests/scenarios/pfs1_get_a_simple_path.yaml#L8-L11). So, the value [`50 * self.environment["pfs_fee"]`](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/utils/configuration/settings.py#L94-L97) is used. The `pfs_fee` itself is also not set ... I didn't find were the value is defined after a quick look, but the value was recently changed.
- The deposit seems to use the `balance_per_node` as the lower bound, [instead of the high bound for the deposit](https://github.com/raiden-network/scenario-player/blob/e74f04644a902ce71421373ea23f244f434b8654/scenario_player/runner.py#L604-L605). So it looks the fix is to change the approve to use `max_funding` for the approval instead.

I will double check the values to make sure the above analysis is right

**Comment by karlb** [comment]
I could reproduce this consistently, but manually resetting my allowance to zero in the RDN contract solved the problem. So this seems to be caused by allowances being left over from previous operations (e.g. failed SP startups).

**Comment by hackaugusto** [comment]
> I could reproduce this consistently, but manually resetting my allowance to zero in the RDN contract solved the problem. So this seems to be caused by allowances being left over from previous operations (e.g. failed SP startups).

Yeah, so the RDN smart contract actually requires the allowance being set to `0`. I did not remember that. https://github.com/raiden-network/scenario-player/pull/552 should fix this.

I couldn't figure out why the transaction was sent in the first place. The allowance is set to `UINT256_MAX` to reduce the number of transactions required, so I'd expect to see only one transaction for the allowance. The problem is that I can't check the allowance at the failing block without an archive node.
