### ISSUE TITLE
Tx failed with "Out of gas"

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#570]
During running reclaim this happened.
```
2020-05-15 12:49:06.957787 [debug    ] Transaction sent               [raiden.network.rpc.client] args=(b'\xe0\r\xb8r|E\xa6q\x1a\xaf\x1c9\xe0\xbf\xb3\xdb\xf1\x15@\xb0', 8000000000000000000) eth_node=<EthClient.GETH: 'geth'> from_address=0x7B78e7Cdde3061c48afa76e3eF79a9Ef9325cD71 function_name=transfer gas_price=24901854934 kwargs={} node=0x7B78e7Cdde3061c48afa76e3eF79a9Ef9325cD71 nonce=7 startgas=48107 to_address=0x6B175474E89094C44Da98b954EedeAC495271d0F token=dd902baa-4de3-4f9d-943f-c3ec0305cd64 transaction_hash=0xc53faf78b78de8bae45a55da5e1c55cb13f36c7b83652408026b9413cdb3bd5b value=0
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/__main__.py", line 9, in <module>
    main()
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 147, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 181, in wrapper
    return func(*args, environment=_load_environment(environment), **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 515, in reclaim_eth
    account=account,
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/utils/reclaim.py", line 241, in reclaim_erc20
    token.transfer(account.address, TokenAmount(drain_amount))
  File "/Users/paul/Projects/brainbot/raiden/raiden/network/proxies/token.py", line 238, in transfer
    "Call to transfer failed for unknown reason. Please make sure the "
raiden.exceptions.RaidenRecoverableError: Call to transfer failed for unknown reason. Please make sure the contract is a valid ERC20 token.
```

The tx in question: https://etherscan.io/tx/0xc53faf78b78de8bae45a55da5e1c55cb13f36c7b83652408026b9413cdb3bd5b

**Comment by palango** [comment]
Hans't been seen in a while. Let's reopen if it happens again.
