### ISSUE TITLE
SP doesn't check UDC token balance on mainnet branch before deposits

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#573]
## Problem Definition 

I have tried running the BF4 scenario twice on mainnet, and both times it fails with:

```
2020-05-15 13:33:10.944916 [error    ] Exception while running scenario [scenario_player.main] 
Traceback (most recent call last):
  File "/home/jacob/dev/scenario-player/scenario_player/main.py", line 335, in run_
    environment=environment,
  File "/home/jacob/dev/scenario-player/scenario_player/main.py", line 410, in orchestrate
    scenario_runner.run_scenario()
  File "/home/jacob/dev/scenario-player/scenario_player/runner.py", line 351, in run_scenario
    gevent.joinall(greenlets, raise_error=True, count=1)
  File "src/gevent/greenlet.py", line 1002, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 1018, in gevent._greenlet.joinall
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/jacob/dev/scenario-player/scenario_player/runner.py", line 431, in setup_environment_and_run_main_task
    pool.join(raise_error=True)
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/pool.py", line 435, in join
    greenlet._raise_exception()
  File "src/gevent/greenlet.py", line 364, in gevent._greenlet.Greenlet._raise_exception
  File "/home/jacob/dev/scenario-player/.env/lib/python3.7/site-packages/gevent/_compat.py", line 62, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/jacob/dev/scenario-player/scenario_player/utils/token.py", line 136, in userdeposit_maybe_deposit
    target_address, new_total_deposit, userdeposit_proxy.client.get_confirmed_blockhash()
  File "/home/jacob/dev/raiden/raiden/network/proxies/user_deposit.py", line 335, in deposit
    self._deposit_check_result(transaction_hash, token, total_deposit, amount_to_deposit)
  File "/home/jacob/dev/raiden/raiden/network/proxies/user_deposit.py", line 622, in _deposit_check_result
    raise RaidenRecoverableError(msg)
raiden.exceptions.RaidenRecoverableError: Deposit amount already increased after another transaction
```

Scenario log: [scenario-player-run_bf4_multi_payments_same_node_2020-05-15T15:28:18.log](https://github.com/raiden-network/raiden/files/4634681/scenario-player-run_bf4_multi_payments_same_node_2020-05-15T15.28.18.log)

I don't think the node logs are relevant for this issue since it happens during deposit from the "scenario node", but please let me know if they are needed.

**Comment by palango** [comment]
Tracked in https://github.com/raiden-network/scenario-player/issues/572
