### ISSUE TITLE
Error on render of BF6 scenario

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#607]
Description
=========
Current master. Getting the traceback below trying to run BF6 (exactly as on raiden repo), using provided `development.json` environment and replacing `raiden_client` with LC's CLI script:
```
Traceback (most recent call last):
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/main.py", line 347, in run_
    scenario_runner = ScenarioRunner(
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/runner.py", line 267, in __init__
    self.definition = ScenarioDefinition(scenario_file, data_path, self.environment)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/definition.py", line 31, in __init__
    rendered_yaml = yaml_template.render(**asdict(environment))
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in <module>
jinja2.exceptions.UndefinedError: list object has no element 1
```

Expected Behavior
===============
No error, scenario runs

**Comment by karlb** [comment]
This happens when the scenario assigns specific matrix servers to the nodes, but the scenario does not contain any information about matrix servers. The SP could
* look at the `environment` key and fetch the default server list like Raiden itself does
* or just use auto for all nodes
* or we require matrix server information in the environment file

I prefer the first option, since the scenario explicitly asks for different servers.

**Comment by palango** [comment]
I only see the `matrix_server_list` key missing in `development.json`. Isn't adding it the easiest solution short term?

**Comment by ulope** [comment]
Yes having the SP load the list sounds like the cleanest option. 
It should only pass server(s) to the nodes if the scenario asks for it though.

I'm not so sure I like the way the servers are given in BF6 though. This relatively tightly couples the scenario to knowledge about the external infrastructure (e.g. there is now a 5th test transport server, or if we wanted to run this agains production the number of servers might be different).
