### ISSUE TITLE
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#608]
Description
=========
- Latest master
- Current python 3.8 packages (Arch Linux)
- clean venv, nuke `~/.cache/pip` to ensure latest packages (should still respect locks)
- `make install-dev` on `scenario-player`
- Launch:
```
Traceback (most recent call last):
  File "./venv/bin/scenario_player", line 5, in <module>
    from scenario_player.__main__ import main
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/__main__.py", line 1, in <module>
    from gevent import monkey  # isort:skip
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 144 from PyObject
``` 

Probably related to https://github.com/gevent/gevent/issues/1674 and some of the tons of duplicated issues reported there. Seems currently there's some incompatibilities around and specific packages pinning is required.

Expected Behavior
===============
To work

**Comment by palango** [comment]
```
ERROR: raiden 1.1.1 has requirement certifi==2019.3.9, but you'll have certifi 2020.6.20 which is incompatible.
ERROR: raiden 1.1.1 has requirement click==7.0, but you'll have click 7.1.2 which is incompatible.
ERROR: raiden 1.1.1 has requirement eth-utils==1.9.0, but you'll have eth-utils 1.9.5 which is incompatible.
ERROR: raiden 1.1.1 has requirement gevent==20.6.2, but you'll have gevent 20.9.0 which is incompatible.
ERROR: raiden 1.1.1 has requirement greenlet==0.4.16, but you'll have greenlet 0.4.17 which is incompatible.
ERROR: raiden 1.1.1 has requirement idna==2.8, but you'll have idna 2.10 which is incompatible.
ERROR: raiden 1.1.1 has requirement jinja2==2.10.1, but you'll have jinja2 2.11.2 which is incompatible.
ERROR: raiden 1.1.1 has requirement six==1.12.0, but you'll have six 1.15.0 which is incompatible.
ERROR: raiden 1.1.1 has requirement urllib3==1.25.3, but you'll have urllib3 1.25.10 which is incompatible.

**Comment by palango** [comment]
I created https://github.com/raiden-network/scenario-player/issues/610 to improve this but for now the easiest fix is to install the raiden develop.

```sh
cd ../raiden
make install-dev
cd ../scenario-player
make install-dev
