### ISSUE TITLE
reclaim-eth send txs but can't wait for them on goerli

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#616]
Description
=========
After the bunch of txs get sent, an exception is thrown when scenario-player would start waiting for them. Minorish though, as they seem to be properly sent and mined, but it'd be nice to get the waiting feedback afterwards.
```
2020-10-10 20:05:57.257360 [debug    ] Waiting for tx confirmations   [scenario_player.utils.legacy] outstanding=161 timeout_remaining=999
Traceback (most recent call last):
  File "./venv/bin/scenario_player", line 8, in <module>
    sys.exit(main())
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/main.py", line 147, in wrapper
    return func(*args, **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/main.py", line 181, in wrapper
    return func(*args, environment=_load_environment(environment), **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/main.py", line 163, in wrapper
    return func(*args, **kwargs)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/main.py", line 511, in reclaim_eth
    scenario_player.utils.reclaim.reclaim_eth(
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/utils/reclaim.py", line 277, in reclaim_eth
    wait_for_txs(web3, txs, 1000)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/scenario_player/utils/legacy.py", line 90, in wait_for_txs
    if tx["blockNumber"] + 2 < web3.eth.getBlock("latest")["number"]:
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/eth.py", line 217, in getBlock
    result = self.web3.manager.request_blocking(
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/manager.py", line 149, in request_blocking
    response = self._make_request(method, params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/manager.py", line 128, in _make_request
    return request_func(method, params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/cache.py", line 134, in middleware
    return make_request(method, params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/cache.py", line 134, in middleware
    return make_request(method, params)
  File "/mnt/sec/Dev/brainbot/raiden/raiden/network/rpc/client.py", line 713, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/normalize_errors.py", line 25, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/formatting.py", line 83, in apply_formatters
    formatter(response["result"]),
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "/mnt/sec/Dev/brainbot/sp/venv/lib/python3.8/site-packages/web3/middleware/validation.py", line 65, in check_extradata_length
    raise ExtraDataLengthError(
web3.exceptions.ExtraDataLengthError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer to http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xf09f928e20407072796c616273206e6f64652d3020f09f928e000000000000001e46191d56fc2c5933d234a8526bed4243a5f8deded78b54a1a1f7e9cd01ba5d576c3308ae6beb6a9d3226a5007a54fc2878a86314f448d61d6f6dabc7850dc800')
```

Expected Behavior
===============
reclaim-eth can wait for txs after sending them

**Comment by palango** [comment]
I'm experiencing the same. However it looks like the POA middleware is installed: https://github.com/raiden-network/scenario-player/blob/64f71a8f75c3d2eb1936625c6fbd9ec01e37cf2e/scenario_player/main.py#L483
