### ISSUE TITLE
JSONDecodeError during reclaim

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#658]
Description
=========

The following crash happened when using the `reclaim` command.
```
Consider installing rusty-rlp to improve pyrlp performance with a rust based backend
2021-02-12 12:39.02 start cmd                      eth_rpc_endpoint=http://parity.goerli.ethnodes.brainbot.com:8545
2021-02-12 12:39.03 Using account                  account=0x5a3B85ece0056aab6de2AB163Ca34EF38838365b
Writing log to /Users/paul/.raiden/scenario-player/scenario-player-reclaim-eth_2021-02-12T12:39:03.log
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/__main__.py", line 9, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 141, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 175, in wrapper
    return func(*args, environment=_load_environment(environment), **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/main.py", line 454, in reclaim_eth
    reclamation_candidates = get_reclamation_candidates(data_path, min_age)
  File "/Users/paul/Projects/brainbot/scenario-player/scenario_player/utils/reclaim.py", line 136, in get_reclamation_candidates
    keyfile_content = json.loads(keyfile.read_text())
  File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.7/3.7.9_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

Expected Behavior
===============
A clear and concise description of what you expected to happen. Do **not** leave anything to the imagination (even if you think it's "common sense", or "obvious").

**Comment by palango** [comment]
Didn't happen again
