### ISSUE TITLE
SP CI problems

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#661]
We have a streak of missing reporting from scenario player runs for the python client.

**Comment by konradkonrad** [comment]
- last "working" client version was at https://github.com/raiden-network/raiden/commit/6aa77d83d0a991fe37bc34c13095174e4e48390b (see https://scenario-player-nightlies.fra1.digitaloceanspaces.com/sp1/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2021-02-14T18:09:18.log.gz)

**Comment by konradkonrad** [comment]
Python client has a problem when setting up the pfs contract:
```
cat /data/scenario-player/scenarios/pfs8_mediator_goes_offline/node_4693_004/run-4693.stderr 
--------- Starting ---------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/cli.py", line 714, in _run
    run_services(kwargs)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/runners.py", line 18, in run_services
    raiden_service = run_raiden_service(**options)
  File "/usr/local/lib/python3.7/site-packages/raiden/ui/app.py", line 455, in run_raiden_service
    raiden_service.start()
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 475, in start
    self._start_transport(chain_state)
  File "/usr/local/lib/python3.7/site-packages/raiden/raiden_service.py", line 583, in _start_transport
    self.transport, self.default_service_registry, BLOCK_ID_LATEST
  File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/transport.py", line 1522, in populate_services_addresses
    block_identifier=block_identifier
  File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 963, in call
    *self.args,
TypeError: call_contract_function() argument after * must be an iterable, not NoneType
ReturnCode.FATAL
```

**Comment by konradkonrad** [comment]
I hope https://github.com/raiden-network/raiden/pull/6863 will fix the issue at hand.
Bad on the other hand is that none of our smoketests caught this!
