### ISSUE TITLE
mfee2 run-5048 failed (eth node read timeout)

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#691]
`node_5048_001/run-5048.stdout`
```
--------- Starting ---------
Command line: /usr/local/bin/raiden --accept-disclaimer --datadir /data/scenarios/mfee2_proportional_fees/node_5048_001 --keystore-path /data/scenarios/mfee2_proportional_fees/node_5048_001/keys --address 0x1D5c55B0EB77C08E2C8b0965CB8a0C39f400d8a9 --password-file /data/scenarios/mfee2_proportional_fees/node_5048_001/password.txt --network-id 5 --sync-check --gas-price fast --eth-rpc-endpoint http://parity.goerli.ethnodes.brainbot.com:8545 --log-config :info,raiden:debug,raiden_contracts:debug,raiden.api.rest.pywsgi:warning --log-json --log-file /data/scenarios/mfee2_proportional_fees/node_5048_001/run-5048.log --disable-debug-logfile --matrix-server https://transport.transport01.raiden.network --api-address 127.0.0.1:36061 --no-web-ui --pathfinding-service-address https://pfs.transport01.raiden.network --gas-price fast --proportional-imbalance-fee 0x59105441977ecD9d805A4f5b060E34676F50F806 0 --flat-fee 0x59105441977ecD9d805A4f5b060E34676F50F806 0 --pathfinding-max-paths 5 --routing-mode pfs --development-environment unstable --environment-type development --pathfinding-max-fee 50000000000000000 --proportional-fee 0x59105441977ecD9d805A4f5b060E34676F50F806 10000
Welcome to Raiden, version 2.0.1.dev287+ge61427336!
+------------------------------------------------------------------------+
| This is a Beta version of experimental open source software released   |
| as a test version under an MIT license and may contain errors and/or   |
| bugs. No guarantee or representation whatsoever is made regarding its  |
| suitability (or its use) for any purpose or regarding its compliance   |
| with any applicable laws and regulations. Use of the software is at    |
| your own risk and discretion and by using the software you warrant and |
| represent that you have read this disclaimer, understand its contents, |
| assume all risk related thereto and hereby release, waive, discharge   |
| and covenant not to hold liable Brainbot Labs Establishment or any of  |
| its officers, employees or affiliates from and for any direct or       |
| indirect damage resulting from the software or the use thereof.        |
| Such to the extent as permissible by applicable laws and regulations.  |
|                                                                        |
| Privacy warning: Please be aware, that by using the Raiden Client,     |
| among others your Ethereum address, channels, channel deposits,        |
| settlements and the Ethereum address of your channel counterparty will |
| be stored on the Ethereum chain, i.e. on servers of Ethereum node      |
| operators and ergo are to a certain extent publicly available. The     |
| same might also be stored on systems of parties running Raiden nodes   |
| connected to the same token network. Data present in the Ethereum      |
| chain is very unlikely to be able to be changed, removed or deleted    |
| from the public arena.                                                 |
|                                                                        |
| Also be aware, that data on individual Raiden token transfers will be  |
| made available via the Matrix protocol to the recipient,               |
| intermediating nodes of a specific transfer as well as to the Matrix   |
| server operators, see Raiden Transport Specification.                  |
+------------------------------------------------------------------------+
```
(---^ stopped after disclaimer)

`node_5048_001/run-5048.stderr` 
```
--------- Starting ---------
KeyboardInterrupt
2021-08-18T17:41:46Z
```

`node_5048_003/run-5048.stderr`
```
--------- Starting ---------
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/gevent/_socketcommon.py", line 693, in recv_into
    self._wait(self._read_event)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 337, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/ui/cli.py", line 721, in _run
    run_services(kwargs)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/ui/runners.py", line 18, in run_services
    raiden_service = run_raiden_service(**options)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/ui/app.py", line 306, in run_raiden_service
    check_ethereum_chain_id(chain_id, web3)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/ui/checks.py", line 108, in check_ethereum_chain_id
    node_chain_id = ChainID(web3.eth.chain_id)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/eth.py", line 463, in chain_id
    return self._chain_id()
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/module.py", line 60, in caller
    null_result_formatters)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/manager.py", line 186, in request_blocking
    response = self._make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/manager.py", line 147, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 84, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
    return make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 114, in middleware
    return make_request(method, params)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/providers/rpc.py", line 91, in make_request
    **self.get_request_kwargs()
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/web3/_utils/request.py", line 48, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)  # type: ignore
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='parity.goerli.ethnodes.brainbot.com', port=8545): Read timed out. (read timeout=10)
ReturnCode.FATAL
```

SP log indicates it failed during initial deposit

**Comment by palango** [comment]
Outdated by now, feel free to reopen if necessary.
