### ISSUE TITLE
Chain parameter not validated correctly

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#8]
Running a scenario with `--chain <chain>` instead of `--chain <chain>:<rpc_url>` fails too late:

```
Writing log to scenario-player_close_channel_one_channel.yaml_2019-05-07T17:36:24.log
2019-05-07 17:36:25.097544 [info     ] Using account                  [raiden.scenario_player.main] account=0x8f5EA3Bb3E99C317b8745918F6973f7AfBF659c3
2019-05-07 17:36:25.313267 [debug    ] Data path                      [raiden.scenario_player.runner] path=PosixPath('/root/.raiden/scenario-player/scenarios/close_channel_one_channel')
2019-05-07 17:36:25.313839 [info     ] Run number                     [raiden.scenario_player.runner] run_number=0
2019-05-07 17:36:25.314233 [info     ] Using chain                    [raiden.scenario_player.runner] chain=kovan
Traceback (most recent call last):
  File "/opt/venv/bin/scenario-player", line 11, in <module>
    load_entry_point('raiden-scenario-player==0.0.0', 'console_scripts', 'scenario-player')()
  File "/opt/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/opt/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/raiden/scenario_player/main.py", line 129, in main
    runner = ScenarioRunner(account, chain_rpc_urls, auth, Path(data_path), scenario_file)
  File "/opt/venv/lib/python3.7/site-packages/raiden/scenario_player/runner.py", line 97, in __init__
    gas_price_strategy=self.scenario.gas_price_strategy,
  File "/opt/venv/lib/python3.7/site-packages/raiden/network/rpc/client.py", line 468, in __init__
    version = web3.version.node
  File "/opt/venv/lib/python3.7/site-packages/web3/version.py", line 14, in node
    return self.web3.manager.request_blocking("web3_clientVersion", [])
  File "/opt/venv/lib/python3.7/site-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "/opt/venv/lib/python3.7/site-packages/raiden/network/rpc/middleware.py", line 84, in middleware
    return make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/cache.py", line 105, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/middleware/exception_retry_request.py", line 87, in middleware
    return make_request(method, params)
  File "/opt/venv/lib/python3.7/site-packages/web3/providers/rpc.py", line 68, in make_request
    **self.get_request_kwargs()
  File "/opt/venv/lib/python3.7/site-packages/web3/utils/request.py", line 26, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/requests/sessions.py", line 510, in request
    prep = self.prepare_request(req)
  File "/opt/venv/lib/python3.7/site-packages/requests/sessions.py", line 453, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/opt/venv/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/opt/venv/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
```
Instead of failing during request processing, it should fail at cli parsing, possibly [here](https://github.com/raiden-network/scenario-player/blob/3c1597d5f2f558904ab0382faf44bbcf2992659a/raiden/scenario_player/utils.py#L89).

**Comment by christianbrb** [comment]
Is it still an issue?

**Comment by nlsdfnbch** [comment]
Unfortunately yes :<
